### ISSUE TITLE
在跑NWPU-VHR-10数据集时出现的问题

### ISSUE THREAD

**Issue by 777Zhao** [bubbliiiing/yolov7-pytorch#35]
Traceback (most recent call last):
  File "E:/Python_3/yolov7-pytorch-master/train.py", line 552, in <module>
    fit_one_epoch(model_train, model, ema, yolo_loss, loss_history, eval_callback, optimizer, epoch, epoch_step, epoch_step_val, gen, gen_val, UnFreeze_Epoch, Cuda, fp16, scaler, save_period, save_dir, local_rank)
  File "E:\Python_3\yolov7-pytorch-master\utils\utils_fit.py", line 48, in fit_one_epoch
    loss_value      = yolo_loss(outputs, targets, images)
  File "E:\Python_3\yolov7-pytorch-master\nets\yolo_training.py", line 104, in __call__
    bs, as_, gjs, gis, targets, anchors = self.build_targets(predictions, targets, imgs)
  File "E:\Python_3\yolov7-pytorch-master\nets\yolo_training.py", line 406, in build_targets
    matching_bs[i]      = torch.cat(matching_bs[i], dim=0)
RuntimeError: torch.cat(): expected a non-empty list of Tensors
出现这样的问题会和数据集中尺寸大小数量有关系吗？我调了一下输入尺寸也还是会报同样错误。如果不是，请教一下有什么解决办法呢，因为看了一些博客但是里面都没有说明具体原因。谢谢

**Comment by bubbliiiing** [comment]
貌似旧代码？

**Comment by misck** [comment]
老哥，我想问问你跑这个数据集如果不使用预训练权重的话，可以收敛吗？

**Comment by 777Zhao** [comment]
> 貌似旧代码？

是的是的~谢谢B哥

**Comment by 777Zhao** [comment]
> 老哥，我想问问你跑这个数据集如果不使用预训练权重的话，可以收敛吗？

只试了跑四五十个epoch~好像是不能收敛的~

**Comment by 777Zhao** [comment]
> 老哥，我想问问你跑这个数据集如果不使用预训练权重的话，可以收敛吗？

收敛，但是map值似乎不是太高~

**Comment by misck** [comment]
我跑完也是，我跑官方仓库ap50能差不多88 89，跑这个才50多。。。。想问问你跑得结果咋样呀？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月13日(星期二) 晚上8:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [bubbliiiing/yolov7-pytorch] 在跑NWPU-VHR-10数据集时出现的问题 (Issue #35)





  
老哥，我想问问你跑这个数据集如果不使用预训练权重的话，可以收敛吗？
  
收敛，但是map值似乎不是太高~

**Comment by misck** [comment]
我跑的都是300，自己改了个种子，不改种子有90出头。这个是bubbling的的结果。我在想是不是up哪里写错了.....






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月13日(星期二) 晚上8:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [bubbliiiing/yolov7-pytorch] 在跑NWPU-VHR-10数据集时出现的问题 (Issue #35)





  
我跑完也是，我跑官方仓库ap50能差不多88 89，跑这个才50多。。。。想问问你跑得结果咋样呀？
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年9月13日(星期二) 晚上8:37 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [bubbliiiing/yolov7-pytorch] 在跑NWPU-VHR-10数据集时出现的问题 (Issue #35) 老哥，我想问问你跑这个数据集如果不使用预训练权重的话，可以收敛吗？ 收敛，但是map值似乎不是太高~ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
老哥跑多少个epoch作比较的呀

**Comment by bubbliiiing** [comment]
数据共享一下，让我看看

**Comment by 777Zhao** [comment]
> 我跑的都是300，自己改了个种子，不改种子有90出头。这个是bubbling的的结果。我在想是不是up哪里写错了.....
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年9月13日(星期二) 晚上8:51 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [bubbliiiing/yolov7-pytorch] 在跑NWPU-VHR-10数据集时出现的问题 (Issue #35) 我跑完也是，我跑官方仓库ap50能差不多88 89，跑这个才50多。。。。想问问你跑得结果咋样呀？ … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年9月13日(星期二) 晚上8:37 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [bubbliiiing/yolov7-pytorch] 在跑NWPU-VHR-10数据集时出现的问题 (Issue #35) 老哥，我想问问你跑这个数据集如果不使用预训练权重的话，可以收敛吗？ 收敛，但是map值似乎不是太高~ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt; 老哥跑多少个epoch作比较的呀 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

emmm我昨天晚上跑了一下300个epoch,确实也只有56左右

**Comment by 777Zhao** [comment]
> 数据共享一下，让我看看

链接：https://pan.baidu.com/s/1sUcvv5kzixIVbGcBYR213A 
提取码：mkby 
--来自百度网盘超级会员V6的分享

**Comment by 777Zhao** [comment]
> 我跑的都是300，自己改了个种子，不改种子有90出头。这个是bubbling的的结果。我在想是不是up哪里写错了.....
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年9月13日(星期二) 晚上8:51 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [bubbliiiing/yolov7-pytorch] 在跑NWPU-VHR-10数据集时出现的问题 (Issue #35) 我跑完也是，我跑官方仓库ap50能差不多88 89，跑这个才50多。。。。想问问你跑得结果咋样呀？ … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年9月13日(星期二) 晚上8:37 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [bubbliiiing/yolov7-pytorch] 在跑NWPU-VHR-10数据集时出现的问题 (Issue #35) 老哥，我想问问你跑这个数据集如果不使用预训练权重的话，可以收敛吗？ 收敛，但是map值似乎不是太高~ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt; 老哥跑多少个epoch作比较的呀 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

不过用best_epoch_weights是到67左右

**Comment by bubbliiiing** [comment]
我这个不是有自动计算map吗，你没有看过map？

**Comment by bubbliiiing** [comment]
历史的

**Comment by bubbliiiing** [comment]
你这个数据格式让我有点苦恼，你有处理完的么

**Comment by bubbliiiing** [comment]
而且很难理解你的测试集是什么

**Comment by 777Zhao** [comment]
> 你这个数据格式让我有点苦恼，你有处理完的么

链接：https://pan.baidu.com/s/18KFBvdNPxYMW4CxIb4-DCQ 
提取码：aafz 
--来自百度网盘超级会员V6的分享

**Comment by 777Zhao** [comment]
> 而且很难理解你的测试集是什么

只把格式转换了一下，没有其他改动的~

**Comment by 777Zhao** [comment]
> 我这个不是有自动计算map吗，你没有看过map？

是指最后一个epoch跑完后出来的那个map值吗，还是get_map.py计算出来的呀

**Comment by bubbliiiing** [comment]
每隔10个epoch会跑一次map

**Comment by bubbliiiing** [comment]
![image](https://user-images.githubusercontent.com/47347516/190909362-3ec201be-8a0c-44d3-8a47-0f0ec8ed7b1c.png)
20epoch就已经66了……你怎么跑到58……

**Comment by bubbliiiing** [comment]
你是没用预训练吗？

**Comment by misck** [comment]
> 你是没用预训练吗？

是的老师， 都是从零开始训练的，超参也按照您在代码里的设置的，对比了一下和官方代码也是相同的(因为自己改模型的话自己训不了预训练模型，所以干脆从头开始训)。

请问有什么比较好的解决办法么？

**Comment by bubbliiiing** [comment]
官方的超参给我看看

**Comment by bubbliiiing** [comment]
训练指令什么的

**Comment by misck** [comment]
![)CGZM%BYW`QP39H_8(8C CQ](https://user-images.githubusercontent.com/34797664/190911003-7c062c94-b6a5-40b3-97d7-31b752a969dc.png)
指令的话那些可选项我都是没有开的

**Comment by bubbliiiing** [comment]
具体指令呢
我看看

**Comment by misck** [comment]
![image](https://user-images.githubusercontent.com/34797664/190911214-d35e3f4f-9256-478a-8aef-be45dec8351c.png)
如图所示，我把default都加上了，然后直接train.py。
这个是官方的python train.py --workers 8 --device 0 --batch-size 32 --data data/coco.yaml --img 640 640 --cfg cfg/training/yolov7.yaml --weights '' --name yolov7 --hyp data/hyp.scratch.p5.yaml

**Comment by bubbliiiing** [comment]
测试集一样的么？

**Comment by misck** [comment]
是的，直接把txt粘贴过来的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月18日(星期天) 晚上10:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [bubbliiiing/yolov7-pytorch] 在跑NWPU-VHR-10数据集时出现的问题 (Issue #35)





 
测试集一样的么？

**Comment by bubbliiiing** [comment]
你们俩是同一个人吗……用的还是同一个数据集吗……

**Comment by bubbliiiing** [comment]
我发现我对话的不是同一个人……

**Comment by misck** [comment]
> 我发现我对话的不是同一个人……
不是同一个人，是都用的这个数据集QAQ

**Comment by bubbliiiing** [comment]
这个数据集是自己划分了测试集吗

**Comment by bubbliiiing** [comment]
我看了他给的原数据集……是没有划分的，你们俩是咋对起来的

**Comment by bubbliiiing** [comment]
我看了他发的原数据集，没有划分的

**Comment by misck** [comment]
> 我看了他给的原数据集……是没有划分的，你们俩是咋对起来的

我也不知道。。。。我就在网上找的随机划分数据集0.8:0.09:0.1。。。

**Comment by 777Zhao** [comment]
> 你是没用预训练吗？

从0开始训练的。

**Comment by misck** [comment]
是的，没有用




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月18日(星期天) 晚上11:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [bubbliiiing/yolov7-pytorch] 在跑NWPU-VHR-10数据集时出现的问题 (Issue #35)





  
你是没用预训练吗？
  
从0开始训练的。

**Comment by bubbliiiing** [comment]
现在我被弄的非常懵逼 你们俩现在划分的不一样应该 我就不知道啥情况了

**Comment by 777Zhao** [comment]
> 我看了他给的原数据集……是没有划分的，你们俩是咋对起来的

项目里的voc_annotation.py不算是划分吗，只是没有具体到分到不同文件夹中吧
![image](https://user-images.githubusercontent.com/91048624/190914165-53f0847e-71ff-4d05-a715-759371dddb4a.png)

**Comment by misck** [comment]
哦哦哦说错了，v7官方的是没有给划分的，所以网上找的一个，老师你这个库就是用的你的annotation.....




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月18日(星期天) 晚上11:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [bubbliiiing/yolov7-pytorch] 在跑NWPU-VHR-10数据集时出现的问题 (Issue #35)





  
我看了他给的原数据集……是没有划分的，你们俩是咋对起来的
  
项目里的voc_annotation.py不算是划分吗，只是没有具体到分到不同文件夹中吧

**Comment by bubbliiiing** [comment]
这样对比……不太对呢……

**Comment by bubbliiiing** [comment]
测试集都不一样

**Comment by misck** [comment]
那我明天拿这边划分的再跑一下。。。谢谢了泡泡老师




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bubbliiiing/yolov7-pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月18日(星期天) 晚上11:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bubbliiiing/yolov7-pytorch] 在跑NWPU-VHR-10数据集时出现的问题 (Issue #35)





 
测试集都不一样

**Comment by bubbliiiing** [comment]
我用你给的140代是55，还在跑。
![image](https://user-images.githubusercontent.com/47347516/190915090-ef154497-e95f-420b-a3b7-e053e6207b1c.png)

**Comment by bubbliiiing** [comment]
![image](https://user-images.githubusercontent.com/47347516/190917013-41fbe5b8-0ff5-48b5-ac4f-3bfc7b4c8281.png)
这样设置效果好一些

**Comment by bubbliiiing** [comment]
从0开始的话

**Comment by bubbliiiing** [comment]
v7官方是否有设置每个epoch最短step？
我试了我的库，直接300代效果一般，1000代效果会很好，原因是300代没有在高学习率进行足够的搜索。

**Comment by misck** [comment]
我不太理解您的意思，什么叫做在高学习率上足够的搜索？
但是我看源码的话
![image](https://user-images.githubusercontent.com/34797664/191170791-28b45712-968e-4343-ad1d-dc569f0d4e8c.png)
应该就是这一部分，train.py是直接调用

**Comment by misck** [comment]
1.第一个的话，应该是没有的
![image](https://user-images.githubusercontent.com/34797664/191171130-a7816607-6693-40ee-b4d1-8e48d21ee095.png)
2.有点没有理解什么是在高学习率进行足够的搜索？我看v7官方也就是用了混合精度训练。
![image](https://user-images.githubusercontent.com/34797664/191171327-c6e97851-d23a-4503-b2f6-8ef9fa3d7931.png)

**Comment by bubbliiiing** [comment]
那你在用官方库训练的时候，每个epoch有几个step呀

**Comment by misck** [comment]
> 那你在用官方库训练的时候，每个epoch有几个step呀

正常的，batchsize开1的话，有648个step

**Comment by bubbliiiing** [comment]
嗯……你试出来么

**Comment by misck** [comment]
batchsize开成1的话，step是648，也就是数据集800*0.81。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月20日(星期二) 晚上9:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [bubbliiiing/yolov7-pytorch] 在跑NWPU-VHR-10数据集时出现的问题 (Issue #35)





 
那你在用官方库训练的时候，每个epoch有几个step呀

**Comment by bubbliiiing** [comment]
emm……不是很理解。现在我没有很明白你的情况
