### ISSUE TITLE
train.py的时候报错，这个问题改如何解决

### ISSUE THREAD

**Issue by timohaha** [bubbliiiing/yolov7-pytorch#45]
`Start Train
Epoch 1/300:   0%|                                                               | 0/168 [00:00<?, ?it/s<class 'dict'>]Traceback (most recent call last):
  File "train.py", line 552, in <module>
    fit_one_epoch(model_train, model, ema, yolo_loss, loss_history, eval_callback, optimizer, epoch, epoch_step, epoch_step_val, gen, gen_val, UnFreeze_Epoch, Cuda, fp16, scaler, save_period, save_dir, local_rank)
  File "D:\fod_tracking\pytorch-yolov7-deepsort-master\detector\yolov7\utils\utils_fit.py", line 34, in fit_one_epoch
    loss_value      = yolo_loss(outputs, targets, images)
  File "D:\fod_tracking\pytorch-yolov7-deepsort-master\detector\yolov7\nets\yolo_training.py", line 104, in __call__
    bs, as_, gjs, gis, targets, anchors = self.build_targets(predictions, targets, imgs)
  File "D:\fod_tracking\pytorch-yolov7-deepsort-master\detector\yolov7\nets\yolo_training.py", line 406, in build_targets
    matching_bs[i]      = torch.cat(matching_bs[i], dim=0)
RuntimeError: There were no tensor arguments to this function (e.g., you passed an empty list of Tensors), but no fallback function is registered for schema aten::_cat.  This usually means that this function requires a non-empty list of Tensors.  Available functions are [CPU, CUDA, QuantizedCPU, BackendSelect, Named, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, Autocast, Batched, VmapMode].

CPU: registered at aten\src\ATen\CPUType.cpp:2127 [kernel]
CUDA: registered at aten\src\ATen\CUDAType.cpp:2983 [kernel]
QuantizedCPU: registered at aten\src\ATen\QuantizedCPUType.cpp:297 [kernel]
BackendSelect: fallthrough registered at ..\aten\src\ATen\core\BackendSelectFallbackKernel.cpp:3 [backend fallback]
Named: registered at ..\aten\src\ATen\core\NamedRegistrations.cpp:7 [backend fallback]
AutogradOther: registered at ..\torch\csrc\autograd\generated\VariableType_2.cpp:8078 [autograd kernel]
AutogradCPU: registered at ..\torch\csrc\autograd\generated\VariableType_2.cpp:8078 [autograd kernel]
AutogradCUDA: registered at ..\torch\csrc\autograd\generated\VariableType_2.cpp:8078 [autograd kernel]
AutogradXLA: registered at ..\torch\csrc\autograd\generated\VariableType_2.cpp:8078 [autograd kernel]
AutogradPrivateUse1: registered at ..\torch\csrc\autograd\generated\VariableType_2.cpp:8078 [autograd kernel]
AutogradPrivateUse2: registered at ..\torch\csrc\autograd\generated\VariableType_2.cpp:8078 [autograd kernel]
AutogradPrivateUse3: registered at ..\torch\csrc\autograd\generated\VariableType_2.cpp:8078 [autograd kernel]
Tracer: registered at ..\torch\csrc\autograd\generated\TraceType_2.cpp:9654 [kernel]
Autocast: registered at ..\aten\src\ATen\autocast_mode.cpp:258 [kernel]
Batched: registered at ..\aten\src\ATen\BatchingRegistrations.cpp:511 [backend fallback]
VmapMode: fallthrough registered at ..\aten\src\ATen\VmapModeRegistrations.cpp:33 [backend fallback]

Epoch 1/300:   0%|                                                               | 0/168 [00:06<?, ?it/s<class 'dict'>]`

**Comment by timohaha** [comment]
好像是标签做错了，我再检查下

**Comment by bubbliiiing** [comment]
可能是标签，可能是环境
