### ISSUE TITLE
可以出一个用YOLOV7做分割的功能么

### ISSUE THREAD

**Issue by nlw1115** [bubbliiiing/yolov7-pytorch#84]
如题，在检测框出物体后可以进行实例分割。我看官方源代码中有相关拓展，B导可以加入到这个项目里吗？

**Comment by bubbliiiing** [comment]
数据格式太麻烦了

**Comment by chenyutao97** [comment]
Traceback (most recent call last):
  File "D:/yolov7-seg/yolov7-segmentation-main/segment/train.py", line 681, in <module>
    main(opt)
  File "D:/yolov7-seg/yolov7-segmentation-main/segment/train.py", line 577, in main
    train(opt.hyp, opt, device, callbacks)
  File "D:/yolov7-seg/yolov7-segmentation-main/segment/train.py", line 295, in train
    for i, (imgs, targets, paths, _, masks) in pbar:  # batch ------------------------------------------------------
  File "D:\Anaconda3\envs\yolov7\lib\site-packages\tqdm\std.py", line 1178, in __iter__
    for obj in iterable:
  File "D:\yolov7-seg\yolov7-segmentation-main\utils\dataloaders.py", line 171, in __iter__
    yield next(self.iterator)
  File "D:\Anaconda3\envs\yolov7\lib\site-packages\torch\utils\data\dataloader.py", line 530, in __next__
    data = self._next_data()
  File "D:\Anaconda3\envs\yolov7\lib\site-packages\torch\utils\data\dataloader.py", line 570, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "D:\Anaconda3\envs\yolov7\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Anaconda3\envs\yolov7\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\yolov7-seg\yolov7-segmentation-main\utils\segment\dataloaders.py", line 167, in __getitem__
    masks = (torch.from_numpy(masks) if len(masks) else torch.zeros(1 if self.overlap else nl, img.shape[0] //
TypeError: can't convert np.ndarray of type numpy.uint16. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.请问b导遇见过这种问题吗

**Comment by bubbliiiing** [comment]
没有uint16，你改成uint8差不多
